import jsPDF from 'jspdf';

export function generateReportPdf(reportData, submissionMeta, isTutorView) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  
  let y = margin;

  const drawFooter = () => {
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      const text = "Generated by Multi-Language Code Plagiarism & Logic Contradiction Engine — for academic review purposes only";
      const textWidth = doc.getTextWidth(text);
      doc.text(text, (pageWidth - textWidth) / 2, pageHeight - 10);
    }
  };

  const checkPageBreak = (neededHeight) => {
    if (y + neededHeight > pageHeight - margin - 15) { // 15 for footer space
      doc.addPage();
      y = margin;
    }
  };

  const addText = (text, size, style, color = [0, 0, 0], spacing = 5) => {
    if (!text) return;
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(String(text), maxLineWidth);
    
    lines.forEach(line => {
      checkPageBreak(size * 0.35 + 2);
      doc.text(line, margin, y);
      y += (size * 0.35 + 2);
    });
    y += spacing;
  };

  // 1. Title
  addText(`Code Analysis Report: ${submissionMeta.assessmentTitle || 'Assessment'}`, 16, "bold", [0, 0, 0], 8);
  
  if (isTutorView && submissionMeta.studentName) {
    addText(`Student: ${submissionMeta.studentName}`, 12, "normal", [100, 100, 100], 8);
  }
  if (!isTutorView) {
    addText(`Submission Date: ${new Date(submissionMeta.submittedAt).toLocaleString()}`, 12, "normal", [100, 100, 100], 8);
  }
  
  y += 5;

  // 2. Similarity Score
  addText(`Similarity Score: ${reportData.similarityScore}%`, 14, "bold", [0, 0, 0], 10);

  // 3. Fingerprint match note
  if (reportData.fingerprintMatch) {
    addText(`Note: This matches the common algorithm '${reportData.fingerprintMatch}'. Similarity here is expected.`, 12, "italic", [50, 50, 150], 10);
  }

  // 4. Structural Evidence
  addText("Structural Evidence:", 14, "bold", [0, 0, 0], 5);
  if (reportData.structuralEvidence && reportData.structuralEvidence.length > 0) {
    reportData.structuralEvidence.forEach(ev => {
      addText(`• ${ev}`, 12, "normal", [0, 0, 0], 3);
    });
  } else {
    addText("None provided.", 12, "italic", [100, 100, 100], 5);
  }
  y += 5;

  // 5. Logic Issues
  addText("Logic Issues:", 14, "bold", [0, 0, 0], 5);
  if (reportData.contradictions && reportData.contradictions.length > 0) {
    reportData.contradictions.forEach(con => {
      addText(`• [${con.type}] ${con.description}`, 12, "normal", [0, 0, 0], 3);
    });
  } else {
    addText("None detected.", 12, "italic", [100, 100, 100], 5);
  }
  y += 5;

  // 6. Full LLM report text
  if (reportData.llmReportText) {
    addText("Detailed LLM Report:", 14, "bold", [0, 0, 0], 5);
    addText(reportData.llmReportText, 11, "normal", [50, 50, 50], 10);
  }

  // 7. Tutor Note
  if (reportData.tutorNote) {
    addText("Tutor Note:", 14, "bold", [0, 0, 0], 5);
    addText(reportData.tutorNote, 12, "normal", [0, 0, 0], 10);
  }

  // 8. Final Decision
  if (reportData.decision) {
    addText("Final Decision:", 14, "bold", [0, 0, 0], 5);
    const decisionText = String(reportData.decision).replace('_', ' ').toUpperCase();
    addText(`Decision: ${decisionText}`, 12, "bold", [0, 0, 0], 5);
    
    if (isTutorView) {
      if (reportData.decidedBy) addText(`Decided By: ${reportData.decidedBy}`, 11, "normal", [100, 100, 100], 3);
      if (reportData.decidedAt) addText(`Decided At: ${new Date(reportData.decidedAt).toLocaleString()}`, 11, "normal", [100, 100, 100], 3);
    }
  }

  drawFooter();
  doc.save(`report-${submissionMeta.submissionId}.pdf`);
}
